name: "🐛 New Bug Report"
description: Report a bug in existing exporter
labels: ["exporter", "bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you (and sorry!) for finding a bug and making an effort to report it. Please update the title above to describe the bug at glance.
  - type: input
    id: exporter-name
    attributes:
      label: Exporter Name
      description: |
        Please provide the name of the exporter that is bugged.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please provide a clear description of what the bug you encountered is. Please make sure you have tested with the latest version of the exporter before you report a bug.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproducing a bug
      description: Providing a quick and consise way to reproduce the bug will greatly speed up the time it will take us to fix it. Please provide any relevant info you think is relevant.
    validations:
      required: false
  - type: textarea
    id: current-behaviour
    attributes:
      label: Current Behaviour
      description: Please describe the current behaviour of the exporter.
    validations:
      required: false
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behaviour
      description: Please describe the expected behaviour of the exporter.
    validations:
      required: false